# permissions for end users to edit hnews.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hnews-editor-role
rules:
- apiGroups:
  - apps.vadasambar.com
  resources:
  - hnews
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.vadasambar.com
  resources:
  - hnews/status
  verbs:
  - get
