---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - apps.vadasambar.com
  resources:
  - hnews
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.vadasambar.com
  resources:
  - hnews/finalizers
  verbs:
  - update
- apiGroups:
  - apps.vadasambar.com
  resources:
  - hnews/status
  verbs:
  - get
  - patch
  - update
